version: '3.8'

services:
  tradpal-indicator:
    build: .
    volumes:
      - ./output:/app/output:rw
      - ./config:/app/config:ro
      - ./logs:/app/logs:rw
      - ./cache:/app/cache:rw
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - TRADPAL_API_KEY=${TRADPAL_API_KEY:-}
      - TRADPAL_API_SECRET=${TRADPAL_API_SECRET:-}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
      - TEST_ENVIRONMENT=false
      # Secrets Management
      - SECRETS_BACKEND=${SECRETS_BACKEND:-env}  # env, vault, aws-secretsmanager
      - VAULT_ADDR=${VAULT_ADDR:-}
      - VAULT_TOKEN=${VAULT_TOKEN:-}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      # Monitoring
      - PROMETHEUS_ENABLED=${PROMETHEUS_ENABLED:-false}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT:-8000}
      # Cloud Configuration
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV:-local}  # local, aws, kubernetes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    networks:
      - tradpal-network

  # Prometheus Monitoring (optional)
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - tradpal-network
    profiles:
      - monitoring

  # Grafana Dashboard (optional)
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - tradpal-network
    profiles:
      - monitoring

  # Redis Cache (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - tradpal-network
    profiles:
      - cache

volumes:
  prometheus_data:
  grafana_data:
  redis_data:

networks:
  tradpal-network:
    driver: bridge
