name: tradpal-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - pytest>=7.0.0
  - pip:
    - ccxt>=4.0.0
    - yfinance>=0.2.0
    - python-dotenv>=1.0.0
    - requests>=2.28.0
    - deap>=1.3.0
    - streamlit>=1.28.0
    - plotly>=5.17.0
    - torch>=2.8.0
    - scikit-learn>=1.3.0
    - optuna>=3.0.0
    - shap>=0.42.0
    - redis>=4.5.0
    - fastapi>=0.100.0
    - uvicorn>=0.23.0
    - pydantic>=2.0.0