name: tradpal-env
channels:
  - conda-forge
  - defaults
  - pytorch  # For PyTorch GPU support
dependencies:
  - python=3.10
  - pip
  # Core data science (conda packages with exact versions)
  - pandas=2.1.4
  - numpy=1.24.3
  - matplotlib=3.8.2
  - scipy=1.11.4
  # PyTorch ecosystem (conda for better CUDA support)
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - cpuonly  # Remove this line if you have CUDA GPU
  # Testing
  - pytest=7.4.4
  # Install service-specific packages via pip in each service
  - pip:
    - python-dotenv==1.0.0
    - requests==2.31.0
    - pydantic==2.5.0
    - pydantic-settings==2.1.0
    - structlog==23.2.0
    - prometheus-client==0.19.0
    - psutil==5.9.7
    # Development tools
    - black==24.1.1
    - isort==5.13.2
    - mypy==1.7.1
    - flake8==6.1.0
    - pytest-asyncio==0.21.1
    - pytest-mock==3.12.0