apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: tradpal-security
  labels:
    app: falco
    component: runtime-security
spec:
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      labels:
        app: falco
        component: runtime-security
    spec:
      serviceAccountName: falco
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      hostPID: true
      hostNetwork: true
      securityContext:
        privileged: true
      containers:
      - name: falco
        image: falcosecurity/falco:0.36.2
        securityContext:
          privileged: true
        env:
        - name: FALCO_K8S_API
          value: ""
        - name: FALCO_K8S_API_CERT
          value: ""
        - name: FALCO_K8S_API_KEY
          value: ""
        - name: FALCO_K8S_API_VERIFY
          value: "false"
        - name: FALCO_K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - mountPath: /host/var/run/docker.sock
          name: docker-socket
          readOnly: true
        - mountPath: /host/dev
          name: dev-fs
          readOnly: true
        - mountPath: /host/proc
          name: proc-fs
          readOnly: true
        - mountPath: /host/boot
          name: boot-fs
          readOnly: true
        - mountPath: /host/lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /host/usr
          name: usr-fs
          readOnly: true
        - mountPath: /etc/falco
          name: falco-config
          readOnly: true
        - mountPath: /etc/falco/rules.d
          name: falco-rules
          readOnly: true
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: service-account-token
          readOnly: true
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: dev-fs
        hostPath:
          path: /dev
      - name: proc-fs
        hostPath:
          path: /proc
      - name: boot-fs
        hostPath:
          path: /boot
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-fs
        hostPath:
          path: /usr
      - name: falco-config
        configMap:
          name: falco-config
      - name: falco-rules
        configMap:
          name: tradpal-falco-rules
      - name: service-account-token
        projected:
          sources:
          - serviceAccountToken:
              audience: https://kubernetes.default.svc.cluster.local
              expirationSeconds: 3600
              path: token